name: 'Setup League Client' 
description: 'Installs the latest version of the League of Legends client.'
author: 'Mikael Dúi Bolinder'
branding:
  icon: 'trending-up'  
  color: 'yellow'
inputs:
  username:
    description: 'The username of a League of Legends account.'
    required: true
    type: string
  password:
    description: 'The password for the League of Legends account.'
    required: true
    type: string
  region:
    description: 'The region of the League of Legends account, e.g. "NA".'
    required: true
    type: string
  cache:
    description: 'Enables caching of the League Client for use in multiple workflow runs.'
    required: false
    type: boolean
    default: false
outputs:
  lcu-password:
    description: "The League Client Session Password. It's NOT your account password."
    value: ${{ steps.windows.outputs.lcu-password }}
  lcu-port:
    description: 'The League Client Port. Used for communicating with it using HTTPS/WSS.'
    value: ${{ steps.windows.outputs.lcu-port }}
  lcu-directory:
    description: 'The League Client Installation Directory.'
    value: ${{ steps.windows.outputs.lcu-directory }}

runs:
  using: "composite"
  steps:  
    - name: "Ensure it's running on Windows"
      if: ${{ runner.os != 'Windows' }}
      uses: actions/github-script@v3
      with:
        script: core.setFailed('This action must be run on Windows!')
        
    - name: Enable cache
      if: ${{ runner.os == 'Windows' && inputs.cache == 'true' }}
      uses: actions/cache@v2
      with:
        path: |
          C:\Riot Games
          !C:\Riot Games\League of Legends\Game
          !C:\Riot Games\League of Legends\Plugins\rcp-be-lol-game-data
        key: ${{ runner.os }}-league-client-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job_id }}
        restore-keys: |
          ${{ runner.os }}-league-client-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job_id }}
          ${{ runner.os }}-league-client-${{ github.run_id }}-${{ github.run_attempt }}-
          ${{ runner.os }}-league-client-${{ github.run_id }}-
          ${{ runner.os }}-league-client-

    - name: Setup League Client on Windows
      if: ${{ runner.os == 'Windows' }}
      id: windows
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH/Windows/Setup-LeagueClient.ps1'
      env:
        LOL_USERNAME: ${{ inputs.username }}
        LOL_PASSWORD: ${{ inputs.password }}
        LOL_REGION: ${{ inputs.region }}
