name: 'Setup League Client' 
description: 'Installs the latest version of the League of Legends client.'
author: 'Mikael Dúi Bolinder'
branding:
  icon: 'trending-up'  
  color: 'yellow'
inputs:
  username:
    description: 'The username of a League of Legends account.'
    required: true
    type: string
  password:
    description: 'The password for the League of Legends account.'
    required: true
    type: string
  region:
    description: 'The region of the League of Legends account, e.g. "NA".'
    required: true
    type: string
outputs:
  lcu-password:
    description: "The League Client Session Password. It's NOT your account password."
    value: ${{ steps.linux.outputs.lcu-password }}${{ steps.windows.outputs.lcu-password }}
  lcu-port:
    description: 'The League Client Port. Used for communicating with it using HTTPS/WSS.'
    value: ${{ steps.linux.outputs.lcu-port }}${{ steps.windows.outputs.lcu-port }}
  lcu-directory:
    description: 'The League Client Installation Directory.'
    value: ${{ steps.linux.outputs.lcu-directory }}${{ steps.windows.outputs.lcu-directory }}

runs:
  using: "composite"
  steps:  
    - name: "Ensure it's running on Windows"
      if: ${{ runner.os != 'Windows' && runner.os != 'Linux' }}
      uses: actions/github-script@v3
      with:
        script: core.setFailed('This action must be run on Linux or Windows!')
        
    - name: Setup League Client on Linux
      if: ${{ runner.os == 'Linux' }}
      id: linux
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH/Linux/Setup-LeagueClient.ps1'
      env:
        LOL_USERNAME: ${{ inputs.username }}
        LOL_PASSWORD: ${{ inputs.password }}
        LOL_REGION: ${{ inputs.region }}

    - name: Setup League Client on Windows
      if: ${{ runner.os == 'Windows' }}
      id: windows
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH/Windows/Setup-LeagueClient.ps1'
      env:
        LOL_USERNAME: ${{ inputs.username }}
        LOL_PASSWORD: ${{ inputs.password }}
        LOL_REGION: ${{ inputs.region }}