name: Daily Test (@ea5ea07)
on:
  schedule:
    - cron:  '0 14 * * *'
  workflow_dispatch:
concurrency: lol
jobs:
  install:
    name: Test the action
    runs-on: windows-latest
    steps:

      - name: Setup the League Client
        id: league-client
        uses: mikaeldui/setup-league-client@ea5ea0748d459cb8e4bade9d50d2f81b70f009f7
        with:
          username: ${{ secrets.LOL_USERNAME }}
          password: ${{ secrets.LOL_PASSWORD }}
          region: ${{ secrets.LOL_REGION }}

      - name: Test outputs
        uses: actions/github-script@v7
        with:
          script: |
            "${{ steps.league-client.outputs.lcu-password }}".length === 0 && core.setFailed("No LCU Password Output");
            "${{ steps.league-client.outputs.lcu-port }}".length === 0 && core.setFailed("No LCU Port Output");
            "${{ steps.league-client.outputs.lcu-directory }}".length === 0 && core.setFailed("No LCU Directory Output");
